package aps.sumo;

// Generated 09-Aug-2016 19:11:22 by Hibernate Tools 4.0.0

/**
 * ApsAdminEmail generated by hbm2java
 */
public class ApsAdminEmail implements java.io.Serializable {

    private Integer idapsAdminEmail;
    private String email;
    private String pass;
    private String host;
    private String port;
    private String timeOut;

    public ApsAdminEmail()
    {
    }

    public ApsAdminEmail(String email, String pass, String host, String port, String timeOut)
    {
	this.email = email;
	this.pass = pass;
	this.host = host;
	this.port = port;
	this.timeOut = timeOut;
    }

    public Integer getIdapsAdminEmail()
    {
	return this.idapsAdminEmail;
    }

    public void setIdapsAdminEmail(Integer idapsAdminEmail)
    {
	this.idapsAdminEmail = idapsAdminEmail;
    }

    public String getEmail()
    {
	return this.email;
    }

    public void setEmail(String email)
    {
	this.email = email;
    }

    public String getPass()
    {
	return this.pass;
    }

    public void setPass(String pass)
    {
	this.pass = pass;
    }

    public String getHost()
    {
	return this.host;
    }

    public void setHost(String host)
    {
	this.host = host;
    }

    public String getPort()
    {
	return this.port;
    }

    public void setPort(String port)
    {
	this.port = port;
    }

    public String getTimeOut()
    {
	return this.timeOut;
    }

    public void setTimeOut(String timeOut)
    {
	this.timeOut = timeOut;
    }

}
