package aps.sumo;

// Generated 08-Aug-2016 22:12:54 by Hibernate Tools 4.0.0

/**
 * ApsWpdatatable3Id generated by hbm2java
 */
public class ApsWpdatatable3Id implements java.io.Serializable {

    private int wdtId;
    private Integer id;
    private String email;
    private String isoddsalertenabled;
    private Float betfairtrigger;
    private Float smarketstrigger;
    private Float batdaqtrigger;
    private Float matchbooktrigger;

    public ApsWpdatatable3Id()
    {
    }

    public ApsWpdatatable3Id(int wdtId)
    {
	this.wdtId = wdtId;
    }

    public ApsWpdatatable3Id(int wdtId, Integer id, String email, String isoddsalertenabled, Float betfairtrigger, Float smarketstrigger, Float batdaqtrigger, Float matchbooktrigger)
    {
	this.wdtId = wdtId;
	this.id = id;
	this.email = email;
	this.isoddsalertenabled = isoddsalertenabled;
	this.betfairtrigger = betfairtrigger;
	this.smarketstrigger = smarketstrigger;
	this.batdaqtrigger = batdaqtrigger;
	this.matchbooktrigger = matchbooktrigger;
    }

    public int getWdtId()
    {
	return this.wdtId;
    }

    public void setWdtId(int wdtId)
    {
	this.wdtId = wdtId;
    }

    public Integer getId()
    {
	return this.id;
    }

    public void setId(Integer id)
    {
	this.id = id;
    }

    public String getEmail()
    {
	return this.email;
    }

    public void setEmail(String email)
    {
	this.email = email;
    }

    public String getIsoddsalertenabled()
    {
	return this.isoddsalertenabled;
    }

    public void setIsoddsalertenabled(String isoddsalertenabled)
    {
	this.isoddsalertenabled = isoddsalertenabled;
    }

    public Float getBetfairtrigger()
    {
	return this.betfairtrigger;
    }

    public void setBetfairtrigger(Float betfairtrigger)
    {
	this.betfairtrigger = betfairtrigger;
    }

    public Float getSmarketstrigger()
    {
	return this.smarketstrigger;
    }

    public void setSmarketstrigger(Float smarketstrigger)
    {
	this.smarketstrigger = smarketstrigger;
    }

    public Float getBatdaqtrigger()
    {
	return this.batdaqtrigger;
    }

    public void setBatdaqtrigger(Float batdaqtrigger)
    {
	this.batdaqtrigger = batdaqtrigger;
    }

    public Float getMatchbooktrigger()
    {
	return this.matchbooktrigger;
    }

    public void setMatchbooktrigger(Float matchbooktrigger)
    {
	this.matchbooktrigger = matchbooktrigger;
    }

    public boolean equals(Object other)
    {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof ApsWpdatatable3Id))
	    return false;
	ApsWpdatatable3Id castOther = (ApsWpdatatable3Id) other;

	return (this.getWdtId() == castOther.getWdtId()) && ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId()))) && ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null && castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
		&& ((this.getIsoddsalertenabled() == castOther.getIsoddsalertenabled()) || (this.getIsoddsalertenabled() != null && castOther.getIsoddsalertenabled() != null && this.getIsoddsalertenabled().equals(castOther.getIsoddsalertenabled())))
		&& ((this.getBetfairtrigger() == castOther.getBetfairtrigger()) || (this.getBetfairtrigger() != null && castOther.getBetfairtrigger() != null && this.getBetfairtrigger().equals(castOther.getBetfairtrigger())))
		&& ((this.getSmarketstrigger() == castOther.getSmarketstrigger()) || (this.getSmarketstrigger() != null && castOther.getSmarketstrigger() != null && this.getSmarketstrigger().equals(castOther.getSmarketstrigger())))
		&& ((this.getBatdaqtrigger() == castOther.getBatdaqtrigger()) || (this.getBatdaqtrigger() != null && castOther.getBatdaqtrigger() != null && this.getBatdaqtrigger().equals(castOther.getBatdaqtrigger())))
		&& ((this.getMatchbooktrigger() == castOther.getMatchbooktrigger()) || (this.getMatchbooktrigger() != null && castOther.getMatchbooktrigger() != null && this.getMatchbooktrigger().equals(castOther.getMatchbooktrigger())));
    }

    public int hashCode()
    {
	int result = 17;

	result = 37 * result + this.getWdtId();
	result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
	result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
	result = 37 * result + (getIsoddsalertenabled() == null ? 0 : this.getIsoddsalertenabled().hashCode());
	result = 37 * result + (getBetfairtrigger() == null ? 0 : this.getBetfairtrigger().hashCode());
	result = 37 * result + (getSmarketstrigger() == null ? 0 : this.getSmarketstrigger().hashCode());
	result = 37 * result + (getBatdaqtrigger() == null ? 0 : this.getBatdaqtrigger().hashCode());
	result = 37 * result + (getMatchbooktrigger() == null ? 0 : this.getMatchbooktrigger().hashCode());
	return result;
    }

}
