package aps.sumo;

// Generated 08-Aug-2016 22:12:54 by Hibernate Tools 4.0.0

/**
 * ApsWpdatatable3 generated by hbm2java
 */
public class ApsWpdatatable3 implements java.io.Serializable {

    private ApsWpdatatable3Id id;

    public ApsWpdatatable3()
    {
    }

    public ApsWpdatatable3(ApsWpdatatable3Id id)
    {
	this.id = id;
    }

    public ApsWpdatatable3Id getId()
    {
	return this.id;
    }

    public void setId(ApsWpdatatable3Id id)
    {
	this.id = id;
    }

}
