package aps.sumo;

// Generated 16-Aug-2016 17:53:54 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * LiveOddsLastRun generated by hbm2java
 */
public class LiveOddsLastRun implements java.io.Serializable {

    private Integer idLiveOdds;
    private String apsBookMaker;
    private String apsExchange;
    private String apsBackUrl;
    private String apsExchangeUrl;
    private BigDecimal apsbackOdds;
    private BigDecimal apslayOdds;
    private String apsOutcomeName;
    private String apsCondition;
    private String apsEventName;
    private BigDecimal apsDifferencePercentage;
    private Date lastUpdated;
    private String apsMatchTime;

    public LiveOddsLastRun()
    {
    }

    public LiveOddsLastRun(String apsBookMaker, String apsExchange)
    {
	this.apsBookMaker = apsBookMaker;
	this.apsExchange = apsExchange;
    }

    public LiveOddsLastRun(String apsBookMaker, String apsExchange, String apsBackUrl, String apsExchangeUrl, BigDecimal apsbackOdds, BigDecimal apslayOdds, String apsOutcomeName, String apsCondition, String apsEventName, BigDecimal apsDifferencePercentage, Date lastUpdated, String apsMatchTime)
    {
	this.apsBookMaker = apsBookMaker;
	this.apsExchange = apsExchange;
	this.apsBackUrl = apsBackUrl;
	this.apsExchangeUrl = apsExchangeUrl;
	this.apsbackOdds = apsbackOdds;
	this.apslayOdds = apslayOdds;
	this.apsOutcomeName = apsOutcomeName;
	this.apsCondition = apsCondition;
	this.apsEventName = apsEventName;
	this.apsDifferencePercentage = apsDifferencePercentage;
	this.lastUpdated = lastUpdated;
	this.apsMatchTime = apsMatchTime;
    }

    public Integer getIdLiveOdds()
    {
	return this.idLiveOdds;
    }

    public void setIdLiveOdds(Integer idLiveOdds)
    {
	this.idLiveOdds = idLiveOdds;
    }

    public String getApsBookMaker()
    {
	return this.apsBookMaker;
    }

    public void setApsBookMaker(String apsBookMaker)
    {
	this.apsBookMaker = apsBookMaker;
    }

    public String getApsExchange()
    {
	return this.apsExchange;
    }

    public void setApsExchange(String apsExchange)
    {
	this.apsExchange = apsExchange;
    }

    public String getApsBackUrl()
    {
	return this.apsBackUrl;
    }

    public void setApsBackUrl(String apsBackUrl)
    {
	this.apsBackUrl = apsBackUrl;
    }

    public String getApsExchangeUrl()
    {
	return this.apsExchangeUrl;
    }

    public void setApsExchangeUrl(String apsExchangeUrl)
    {
	this.apsExchangeUrl = apsExchangeUrl;
    }

    public BigDecimal getApsbackOdds()
    {
	return this.apsbackOdds;
    }

    public void setApsbackOdds(BigDecimal apsbackOdds)
    {
	this.apsbackOdds = apsbackOdds;
    }

    public BigDecimal getApslayOdds()
    {
	return this.apslayOdds;
    }

    public void setApslayOdds(BigDecimal apslayOdds)
    {
	this.apslayOdds = apslayOdds;
    }

    public String getApsOutcomeName()
    {
	return this.apsOutcomeName;
    }

    public void setApsOutcomeName(String apsOutcomeName)
    {
	this.apsOutcomeName = apsOutcomeName;
    }

    public String getApsCondition()
    {
	return this.apsCondition;
    }

    public void setApsCondition(String apsCondition)
    {
	this.apsCondition = apsCondition;
    }

    public String getApsEventName()
    {
	return this.apsEventName;
    }

    public void setApsEventName(String apsEventName)
    {
	this.apsEventName = apsEventName;
    }

    public BigDecimal getApsDifferencePercentage()
    {
	return this.apsDifferencePercentage;
    }

    public void setApsDifferencePercentage(BigDecimal apsDifferencePercentage)
    {
	this.apsDifferencePercentage = apsDifferencePercentage;
    }

    public Date getLastUpdated()
    {
	return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated)
    {
	this.lastUpdated = lastUpdated;
    }

    public String getApsMatchTime()
    {
	return this.apsMatchTime;
    }

    public void setApsMatchTime(String apsMatchTime)
    {
	this.apsMatchTime = apsMatchTime;
    }

}
