package aps.sumo;

// Generated 08-Aug-2016 20:53:29 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * MailLog generated by hbm2java
 */
public class MailLog implements java.io.Serializable {

    private Integer idMailLog;
    private String from;
    private String to;
    private Date lastUpdated;
    private Integer noOfResults;
    private Long averagDifferenceOdds;

    public MailLog()
    {
    }

    public MailLog(String from, String to)
    {
	this.from = from;
	this.to = to;
    }

    public MailLog(String from, String to, Date lastUpdated, Integer noOfResults, Long averagDifferenceOdds)
    {
	this.from = from;
	this.to = to;
	this.lastUpdated = lastUpdated;
	this.noOfResults = noOfResults;
	this.averagDifferenceOdds = averagDifferenceOdds;
    }

    public Integer getIdMailLog()
    {
	return this.idMailLog;
    }

    public void setIdMailLog(Integer idMailLog)
    {
	this.idMailLog = idMailLog;
    }

    public String getFrom()
    {
	return this.from;
    }

    public void setFrom(String from)
    {
	this.from = from;
    }

    public String getTo()
    {
	return this.to;
    }

    public void setTo(String to)
    {
	this.to = to;
    }

    public Date getLastUpdated()
    {
	return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated)
    {
	this.lastUpdated = lastUpdated;
    }

    public Integer getNoOfResults()
    {
	return this.noOfResults;
    }

    public void setNoOfResults(Integer noOfResults)
    {
	this.noOfResults = noOfResults;
    }

    public Long getAveragDifferenceOdds()
    {
	return this.averagDifferenceOdds;
    }

    public void setAveragDifferenceOdds(Long averagDifferenceOdds)
    {
	this.averagDifferenceOdds = averagDifferenceOdds;
    }

}
